ALTER POLICY "memberships_visible_to_self_or_within_tenant" ON "tenant_memberships" TO app_user USING (
        "tenant_memberships"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid
        or "tenant_memberships"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
      );--> statement-breakpoint
ALTER POLICY "memberships_write_within_tenant" ON "tenant_memberships" TO app_user WITH CHECK ("tenant_memberships"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "memberships_update_within_tenant" ON "tenant_memberships" TO app_user USING ("tenant_memberships"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("tenant_memberships"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "memberships_delete_within_tenant" ON "tenant_memberships" TO app_user USING ("tenant_memberships"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "jobs_select_within_tenant" ON "jobs" TO app_user USING ("jobs"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "jobs_insert_within_tenant" ON "jobs" TO app_user WITH CHECK ("jobs"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "jobs_update_within_tenant" ON "jobs" TO app_user USING ("jobs"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("jobs"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "jobs_delete_within_tenant" ON "jobs" TO app_user USING ("jobs"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_type_accounts_select_within_tenant" ON "cost_type_accounts" TO app_user USING ("cost_type_accounts"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_type_accounts_insert_within_tenant" ON "cost_type_accounts" TO app_user WITH CHECK ("cost_type_accounts"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_type_accounts_update_within_tenant" ON "cost_type_accounts" TO app_user USING ("cost_type_accounts"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("cost_type_accounts"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_type_accounts_delete_within_tenant" ON "cost_type_accounts" TO app_user USING ("cost_type_accounts"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_codes_select_within_tenant" ON "cost_codes" TO app_user USING ("cost_codes"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_codes_insert_within_tenant" ON "cost_codes" TO app_user WITH CHECK ("cost_codes"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_codes_update_within_tenant" ON "cost_codes" TO app_user USING ("cost_codes"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("cost_codes"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_codes_delete_within_tenant" ON "cost_codes" TO app_user USING ("cost_codes"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "budgets_select_within_tenant" ON "budgets" TO app_user USING ("budgets"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "budgets_insert_within_tenant" ON "budgets" TO app_user WITH CHECK ("budgets"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "budgets_update_within_tenant" ON "budgets" TO app_user USING ("budgets"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("budgets"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "budgets_delete_within_tenant" ON "budgets" TO app_user USING ("budgets"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "documents_select_within_tenant" ON "documents" TO app_user USING ("documents"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "documents_insert_within_tenant" ON "documents" TO app_user WITH CHECK ("documents"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "documents_update_within_tenant" ON "documents" TO app_user USING ("documents"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("documents"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "documents_delete_within_tenant" ON "documents" TO app_user USING ("documents"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "purchase_orders_select_within_tenant" ON "purchase_orders" TO app_user USING ("purchase_orders"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "purchase_orders_insert_within_tenant" ON "purchase_orders" TO app_user WITH CHECK ("purchase_orders"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "purchase_orders_update_within_tenant" ON "purchase_orders" TO app_user USING ("purchase_orders"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("purchase_orders"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "purchase_orders_delete_within_tenant" ON "purchase_orders" TO app_user USING ("purchase_orders"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_transactions_select_within_tenant" ON "cost_transactions" TO app_user USING ("cost_transactions"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_transactions_insert_within_tenant" ON "cost_transactions" TO app_user WITH CHECK ("cost_transactions"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_transactions_update_within_tenant" ON "cost_transactions" TO app_user USING ("cost_transactions"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("cost_transactions"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "cost_transactions_delete_within_tenant" ON "cost_transactions" TO app_user USING ("cost_transactions"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_defaults_select_within_tenant" ON "allocation_defaults" TO app_user USING ("allocation_defaults"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_defaults_insert_within_tenant" ON "allocation_defaults" TO app_user WITH CHECK ("allocation_defaults"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_defaults_update_within_tenant" ON "allocation_defaults" TO app_user USING ("allocation_defaults"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("allocation_defaults"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_defaults_delete_within_tenant" ON "allocation_defaults" TO app_user USING ("allocation_defaults"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_lines_select_within_tenant" ON "allocation_lines" TO app_user USING ("allocation_lines"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_lines_insert_within_tenant" ON "allocation_lines" TO app_user WITH CHECK ("allocation_lines"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_lines_update_within_tenant" ON "allocation_lines" TO app_user USING ("allocation_lines"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("allocation_lines"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "allocation_lines_delete_within_tenant" ON "allocation_lines" TO app_user USING ("allocation_lines"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employees_select_within_tenant" ON "employees" TO app_user USING ("employees"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employees_insert_within_tenant" ON "employees" TO app_user WITH CHECK ("employees"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employees_update_within_tenant" ON "employees" TO app_user USING ("employees"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("employees"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employees_delete_within_tenant" ON "employees" TO app_user USING ("employees"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employee_rates_select_within_tenant" ON "employee_rates" TO app_user USING ("employee_rates"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employee_rates_insert_within_tenant" ON "employee_rates" TO app_user WITH CHECK ("employee_rates"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employee_rates_update_within_tenant" ON "employee_rates" TO app_user USING ("employee_rates"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("employee_rates"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "employee_rates_delete_within_tenant" ON "employee_rates" TO app_user USING ("employee_rates"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_time_entries_select_within_tenant" ON "labour_time_entries" TO app_user USING ("labour_time_entries"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_time_entries_insert_within_tenant" ON "labour_time_entries" TO app_user WITH CHECK ("labour_time_entries"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_time_entries_update_within_tenant" ON "labour_time_entries" TO app_user USING ("labour_time_entries"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("labour_time_entries"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_time_entries_delete_within_tenant" ON "labour_time_entries" TO app_user USING ("labour_time_entries"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_settings_select_within_tenant" ON "labour_settings" TO app_user USING ("labour_settings"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_settings_insert_within_tenant" ON "labour_settings" TO app_user WITH CHECK ("labour_settings"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_settings_update_within_tenant" ON "labour_settings" TO app_user USING ("labour_settings"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid) WITH CHECK ("labour_settings"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "labour_settings_delete_within_tenant" ON "labour_settings" TO app_user USING ("labour_settings"."tenant_id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid);